// ============================================
// FILE: lib/google-drive-helpers.ts
// NEW: Centralized Google Drive URL helpers
// ============================================

/**
 * Generate Google Drive URLs from file IDs
 * Sử dụng public API của Google Drive (không cần authentication)
 */
export function generateDriveUrls(
  fileId: string,
  thumbnailId: string | null = null,
): {
  photoUrl: string;
  thumbnailUrl: string;
  webViewLink: string;
} {
  return {
    // Direct download URL (không cần auth)
    photoUrl: `https://drive.google.com/uc?export=download&id=${fileId}`,

    // Thumbnail URL (auto-generated by Google, size=400px width)
    thumbnailUrl: thumbnailId
      ? `https://drive.google.com/thumbnail?id=${thumbnailId}&sz=w400`
      : `https://drive.google.com/thumbnail?id=${fileId}&sz=w400`,

    // Web view URL (open in browser)
    webViewLink: `https://drive.google.com/file/d/${fileId}/view`,
  };
}

/**
 * Get thumbnail URL with custom size
 */
export function getDriveThumbnailUrl(
  fileId: string,
  size: number = 400,
): string {
  return `https://drive.google.com/thumbnail?id=${fileId}&sz=w${size}`;
}

/**
 * Get direct download URL
 */
export function getDirectDownloadUrl(fileId: string): string {
  return `https://drive.google.com/uc?export=download&id=${fileId}`;
}

/**
 * Get web view URL (open in Google Drive UI)
 */
export function getWebViewUrl(fileId: string): string {
  return `https://drive.google.com/file/d/${fileId}/view`;
}

/**
 * Validate Google Drive file ID format
 */
export function isValidDriveFileId(fileId: string): boolean {
  // Google Drive file IDs are typically 33-44 characters
  // Format: alphanumeric, hyphens, underscores
  return /^[a-zA-Z0-9_-]{25,50}$/.test(fileId);
}

/**
 * Extract file ID from Google Drive URL
 */
export function extractFileIdFromUrl(url: string): string | null {
  // Match patterns:
  // - https://drive.google.com/file/d/{fileId}/view
  // - https://drive.google.com/uc?id={fileId}
  // - https://drive.google.com/open?id={fileId}

  const patterns = [/\/file\/d\/([a-zA-Z0-9_-]+)/, /[?&]id=([a-zA-Z0-9_-]+)/];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) {
      return match[1];
    }
  }

  return null;
}

/**
 * Check if file is accessible (public or shared)
 * Note: This requires making a HEAD request to Google Drive
 */
export async function isDriveFileAccessible(fileId: string): Promise<boolean> {
  try {
    const url = getDirectDownloadUrl(fileId);
    const response = await fetch(url, { method: "HEAD" });
    return response.ok;
  } catch (error) {
    return false;
  }
}

/**
 * Get file metadata from Google Drive (if public)
 */
export async function getDriveFileMetadata(fileId: string): Promise<{
  name: string;
  mimeType: string;
  size: number;
} | null> {
  try {
    // Use Google Drive API v3 (public files only)
    const response = await fetch(
      `https://www.googleapis.com/drive/v3/files/${fileId}?fields=name,mimeType,size&key=${process.env.GOOGLE_API_KEY}`,
      { method: "GET" },
    );

    if (!response.ok) {
      return null;
    }

    return await response.json();
  } catch (error) {
    console.error("Error fetching Drive metadata:", error);
    return null;
  }
}
